### ISSUE TITLE
Source for controller changes

### ISSUE THREAD

**Issue by glebm** [krishenriksen/Half-Life-rg351p#2]
Hi, I'm working on a clean package for batocera.linux in https://github.com/batocera-linux/batocera.linux/pull/2703

I've noticed that the keyboard.cfg here has things like `+SelectHold` that aren't defined anywhere in the source. Have you perhaps uploaded the wrong source without your controller patches?

**Comment by krishenriksen** [comment]
Answered on Discord.

**Comment by glebm** [comment]
From Discord, these configs are responsible for the magic:

[keyboard-and-autoexec-cfg.zip](https://github.com/krishenriksen/Half-Life-rg351p/files/5755786/keyboard-and-autoexec-cfg.zip)
